---
# - import_playbook: other/install_common.yml
# - import_playbook: other/install_docker.yml

# - import_playbook: python/install_python_pip.yml
# - import_playbook: python/install_uv.yml
# - import_playbook: python/install_conda.yml
# - import_playbook: python/install_poetry.yml
# - import_playbook: python/install_pyenv.yml

# - import_playbook: java/install_open_jdk.yml
# - import_playbook: java/install_oracle_jdk.yml
# - import_playbook: java/install_ibm_semeru_jdk.yml
# - import_playbook: java/install_eclipse_temurin_jdk.yml
# - import_playbook: java/install_azul_zulu_jdk.yml
# - import_playbook: java/install_aws_corretto_jdk.yml
# - import_playbook: java/install_microsoft_open_jdk.yml

# - import_playbook: nodejs/install_node.yml
# - import_playbook: nodejs/install_nvm.yml

# - import_playbook: nginx/install_nginx.yml

# - import_playbook: apache/install_tomcat.yml
# - import_playbook: apache/install_apache.yml
# - import_playbook: jboss/install_wildfly.yml

# - import_playbook: database/mariadb/install_mariadb.yml
# - import_playbook: database/mysql/install_mysql.yml
- import_playbook: database/postgresql/install_postgresql.yml
# - import_playbook: database/mongodb/install_mongodb.yml
# - import_playbook: database/redis/install_redis.yml
