---
- import_playbook: install_common.yml
- import_playbook: python/install_python_pip.yml
- import_playbook: python/install_uv.yml
# - import_playbook: python/install_conda.yml
# - import_playbook: python/install_poetry.yml
# - import_playbook: python/install_pyenv.yml
