---
# - import_playbook: nginx/create_ssl_certificate_demo.ganjianping.com.yml
# - import_playbook: nginx/deploy_site_conf_demo.ganjianping.com.yml

# - import_playbook: database/mariadb/execute_mariadb_sqls.yml
# - import_playbook: database/mysql/execute_mysql_sqls.yml
# - import_playbook: database/postgresql/execute_postgresql_sqls.yml
# - import_playbook: database/mongodb/execute_mongodb_script.yml